import React from 'react';
import NavBarReal from '../NavBar/Real';
import './styles.css';

const Glosario = () => {
    
    const LETRAS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'Ñ', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'];

    const GLOSA = ["enambaia: vegetación corta",
    "ica: duro por congelación",
    "ikaiyagu: quemar un árbol para otra persona",
    "ikamangamata: dibujar o escribir por otra persona",
    "ikama-nalagöna: intentar escribir",
    "-mutu: escribir, pintar, sentado",
    "-möni: escribir, pintar, parado",
    "-tölli: garabatear",
    "-niatakös: resumir",
    "iki: quemar un árbol cerca de sus raíces",
    "charred: árbol quemado",
    "ämisiu: deforestación",
    "idagana: crecer, madurar",
    "ilaia: afuera",
    "yeka: lejos",
    "imuna: presentarse como padre",
    "inakupai: demasiado alto",
    "inaia: invierno",
    "ina-kili: botas de invierno",
    "Ïnenur cellun: cuando pase el invierno",
    "inadora: durante el invierno",
    "inia: dar una canoa",
    "inix: lanza pequeña",
    "inu: arriba",
    "inupai: para usar en invierno",
    "itakön-ökan: adentro",
    "wapan: profundo",
    "italum: del este",
    "iyig-ata: buscar",
    "iya(inia): anclar, amarrar una canoa",
    "iyix-möni: tener en una cesta",
    "aiiuaragu: llamar, avisar",
    "aiiuswana: tostar, cocinar al fuego",
    "ilenata: terminar de construir",
    "iliwönari: poner las manos o dedos en el agua",
    "ilipuku: poner las manos en el fuego",
    "ilana: construir una pared",
    "aiiusu: ladrido fuerte",
    "aioa: tiempo de buena caza",
    "aia: muy dispuesto",
    "aiiu: arreglar una lanza",
    "aias-a: cubrir con tierra, pasto, plumas",
    "amina: un pájaro que baja de su nido hacia el agua",
    "amöni: cubrir",
    "aiel-la: cubrir e irse como un pájaro dejando sus huevos",
    "agamata: cubrir a medias",
    "aiakasi: Todos los peces y aves de aguas profundas u oceánicas",
    "aiagöllum: asesinos de ballenas",
    "aial-amöni: tener un buen cuerpo",
    "aiamas-a: pariente de una pareja cuando uno de los dos murió",
    "aiamak-a: pelear, discutir, insultarse",
    "aiamin-a: ordenar, dar trabajo, mandar a algún lado",
    "ãrugata: preocupado o incómodo al ordenar",
    "a-gãmata: enviar a una persona en vez de a otra",
    "a-gãmur cella: emplear a alguien ocasionalmente",
    "aiami-nûmanãtsiköri: enviar afuera de una casa",
    "a.tölli: dar órdenes de forma rápida a una persona",
    "a-nûãsanöna: apurar a un mensajero o sirviente sin compasión",
    "aiamux-dãtû: pelear aquí y allá o con diversas personas a la vez",
    "a-köna: pelear a flote de cualquier embarcación",
    "a-yella: pelear un poco",
    "aiamak-önnakãki: alguien que no pelea o que no pelea bien",
    "aian: fuego o madera seca para el fuego",
    "-atama: cancer o cualquier enfermedad similar",
    "anaiamgatölia: polillas",
    "aianda: seco",
    "aianna: primero, lo antes posible, lo más temprano",
    "a-mamãgûa: primogenito",
    "aiapar: con poca carne, flaco",
    "aiapux: nutria",
    "aiasi: Una capa de sustancia grasa que se encuentra inmediatamente debajo de la grasa de las ballenas, es más roja que la grasa y no tan gruesa, y separándose de la carne hay una capa más delgada de materia delgada.",
    "a-na; salir para dejar vacía la casa como sucede cuando en mareas muy bajas todos salen afuera para pescar",
    "aiax-möni: formar nudos y dejarlos por un tiempo",
    "aiagata: subir rápido a la superficie y tomar aire para sumergirse como hacen las ballenas cuando levantan sus aletas",
    "aiata: el interior o hueco de la rodilla",
    "aii: que sorpresa!, que extraño!, ay!",
    "aiãkû: madera dura",
    "aiãgû: juntar mariscos por la noche, especialmente mejillones",
    "aigala: luz, inteligente, sabio, hábil",
    "aial-ãkurû: deseo de saber, de aprender",
    "aial-ãkurû.ana: aprender, entender, saber, ser consciente",
    "aii: por supuesto!",
    "aiû: Un gran pez de color blanquecino, con grandes escamas",
    "aiušwãn: cocinar al lado pero no en el fuego como hacen los nativos los huevos",
    "aimû: hacer ocasionalmente, a veces",
    "aink-öna: distribuir",
    "aikãtaka: ir o venir con una lanza en la mano",
    "aikuš: Palos pequeños de uškutta o de otros árboles que recubren y protegen la corteza de los árboles",
    "aifwãgöpi: llevar cestas llenas a bordo",
    "ai-gata: ayudar a un amigo en una pelea o lucha",
    "aim-önapi-û: dar a las personas, compartir, dividir",
    "aim-önapi-ûtas: distribución exacta, tener buenos modales",
    "aim-önapi-ûtasana: distribuir como un experto o de una buena manera",
    "aim-önapi-ûtû: distribuir sentado",
    "anix; malhumorado, malo, perverso",
    "ainigönata: ser más malhumorado, malo, perverso",
    "aipû: Tomar juntos un número de cestas por sus asas, llenas de hongos o cualquier otra cosa",
    "aip’atöpi: poner, traer, subir a bordo una cesta llena de bayas u otras cosas", 
    "aiyêata: Llamar a una persona para que venga",
    "aiyõan: Las plumas de las alas de los pájaros",
    "aiya: ¡Mira! ¿Qué es eso?",
    "aiyella: hacer otro balde",
    "t-aiyialagöna: intentar llamar para ver si alguien va a escuchar o venir",
    "aiyi: llamar o ir a hacer algo, invitar",
    "aiyiella: llamar otra vez",
    "aiyin-köna: salir, como el fuego en una canoa",
    "aiyišönata: convocar una retirada",
    "aiyêikaia: llamar",
    "aiyaiyãgû: Pedir lo que pertenece a otro para conseguirlo por él",
    "aiyi-gãmata: llamar mal una cosa o persona",
    "aiyi-aina: caminar llamando a una persona",
    "aiyi-möci: llamar para venir a pescar",
    "aiyi-nia: Estar bajo o apagado o a punto de extinguirse como un fuego",
    "aiyi-nata: morir, como se extingue el fuego",
    "aiyi-nãmöni: estar a punto de apagarse como una llama o fuego",
    "aiyi-mina: llamar para sentarse junto al fuego",
    "aiyi-ndala: no resistir bien el fuego",
    "aiyitûm-ina: pedir cosas prestadas",
    "aiyitûm-öpi: llamar personas para que suban a bordo",
    "aiyitênaka: buscar llamando a una persona",
    "aiön-tãta: El camino de un derrumbe. El lugar desnudo que queda",
    "aiyiãgû: llamar al propio hijo o esposa",
    "aiyušû: La gruesa corteza de los árboles crecidos",
    "aizag-ãnia: rebelde, obstinado",
    "aizök-a: inmenso, muy grande, enorme",
    "õnaiiûãna: tipo de juego acompañado con cantos y pinturas",
    "iûaian-a: buscar unos tipos de hongos que están escondidos",
    "iûaia: celoso, como un marido o esposa",
    "iûaiaiiya: ser muy celoso",
    "iûaiella: no ser celoso",
    "iûaiatãki: las arterias más grandes. Dada por los celos",
    "iûain: en el borde, al lado",
    "iûain-hikai: junto al mar",
    "iûain-gala: alrededor",
    "iûaš: cortar trozos de grasa en porciones más pequeñas",
    "iûaš-ê: cortar a la mitad cortando con los dientes",
    "iûak-amãtû: levantar con la boca, como un perro a un trozo de carne enterrada",
    "iûak-amãtû-ãna: bajar con la boca",
    "iûmãmata: morder pero solo ligeramente o solo en los bordes",
    "iûalaiakãsi: espada pequeña",
    "iûalagöna: probar mordiendo",
    "iûalãšû: morder y lastimarse",
    "iûalöpata: cazar, atrapar, matar como los perros matan pájaros",
    "iûm-a: morder un pedazo de comida y dar",
    "iûm-alöpata: separar la piel y la carne como los perros",
    "iûan: El tiempo de los cangrejos jóvenes cuando los mayores llevan a los más jóvenes / las estaciones de año que responden a Octubre y noviembre",
    "iûar-a: dolores punzantes en el abdomen",
    "iûat-ênaka: buscar como un perro con la boca",
    "iûia: morder mientras se está acostado",
    "iûãšina: masticar o morder con suavidad",
    "iûãgû: gaviota",
    "iûãlöpata: ver",
    "iûãlux: el nombre de una estrella brillante",
    "iûãm-öni: casi morder",
    "lökaiana: morir, morir en gran número de personas",
    "iûãn-a: bailar, saltar sobre",
    "iûgala: deshacer con los dientes algún tipo de atadura",
    "iûãpûkû: cocinar, poner en el fuego para cocinar",
    "iûga-nari: llevar como una foca los cachorros al mar",
    "iûauisa: movimiento del sedal cuando los peces muerden el anzuelo",
    "iûûkaia: llevar o traer cosas en la boca",
    "iûša: línea de la costa sin playa o con piedras",
    "iûša-nia: correr",
    "iûša-tãsin: Un lugar agradable para el desembarco en una costa abrupta, siendo menos audaz que en otros lugares",
    "iûšãna: comer algo en mal estado",
    "iûsiû: arrancar con la boca",
    "iugûleni: atrapar bajo el agua como un tiburón a su presa",
    "iuna: cola, nalgas",
    "acawaia: vida, espíritu, vigor, alma, fuerza, energía",
    "-nata:  que se despierte algún sentimiento fuerte de ira o terror",
    "acela: pelo corto en el cuerpo humano, piel",
    "acawaia-kurû: odiar, disgustar",
    "acawaia-möni: tratar con odio, tratar mal",
    "açenûwa: mejor",
    "acikam-a: cortar, marcar con un corte",
    "acikam-ata: cortar atravesando de extremo a extremo",
    "acikam-akaia: cortar para arriba",
    "acikam-ãgãmata: errar al cortar, cortar otra cosa al cortar como se hace con el dedo al cortar el pan",
    "acix: algas de árbol",
    "acili-x: enano, deforme, de forma no natural, monstruoso",
    "acinuš: liendres",
    "acönfata: buscar agua con un balde",
    "ašãg-a: canal, paso, estrecho",
    "ašãg-ãna: pasar por un estrecho o paso",
    "abail-a: fuerte, físicamente fuerte, con salud, firme, saludable, enérgico",
    "abail-enata: ganar fuerza",
    "abail-cella: ser un poco más fuerte",
    "abail-a-mût-ãgû: ser capaz",
    "abail-anönnaka: no tener fuerza o energía",
    "abail-anci: puedo hacerlo porque soy fuerte",
    "akêamana: Buscar un árbol o tronco probándolo con cuña y martillo para ver si se parte bien",
    "akaiata: acercar con un palo",
    "akika: hombro",
    "akimakaia: halcón chico",
    "akita: raspar o afeitar con un cuchillo o caracol",
    "-ma: peinarse",
    "akita-lagöna: intentar afeitarse",
    "akita-tas: experto en afeitado",
    "akiya: cangrejos en general, pero especialmente los de extremidades largas",
    "akaiakaiiûa: ¡Qué sorpresa!",
    "akir-köna: estar agarrado con el remo a la orilla, o mantener la canoa al lado de la embarcación remando",
    "akainix: arcoiris",
    "akainix-wöngara: pequeños insectos que cubren las aguas tranquilas, como los estanques, como un fino polvo",
    "akaiya: golpear mientras se está acostado",
    "akiûãna kömamöniyãrum: ahora hay un viento del sur",
    "akiûönari: golpear o atacar en el agua",
    "akiella: golpear e irse o no golpear otra vez",
    "aka: un deslizamiento de tierra, ya sea el curso de la misma, o los escombros, el resultado de la misma",
    "aki: golpe de viento",
    "akidãtû: muchos golpes de viento",
    "akig-aia: marcar un árbol como apropiado para hacer lanzas",
    "akig-ãmata: golpearse sin querer, como un carpintero a su dedo",
    "akig-möni: golpearse a veces",
    "akim-öni: casi golpear. Probar y dejar para el presente un árbol que se encuentra apto para las astas, partiéndolo un poco",
    "aki-lûpaii: derribar y hacer caer",
    "akimãtû: romper el invierno, temporada de vendavales, nieve y sol",
    "akis-iû: Alisar una pieza antes de terminarla",
    "akis-wönari: sumergirse con sonido al agua",
    "akit-eka: tirar con el viento",
    "akit-ûalãšû: gritar de dolor por un golpe de viento",
    "alsöp-i: tener la cara hinchada por el frío",
    "akönûm-ãmaia: muchos árboles cayendo juntos",
    "akãlûaia: lago, laguna, estanque, pantano",
    "akãlûaia-nata: inundado, inundación",
    "akãna: Caer como rocas o escombros desde precipicios, o como una construcción o cualquier cosa apilada",
    "akaui: frío, tener frío",
    "akûa-ši: cortar con una azada",
    "lãšû: golpear, herir, lastimar",
    "akûam-a: cortar leña para el fuego",
    "akûam-ata: cavar",
    "akûam-ãgãmata: cortar leña por otra persona",
    "akûam-alagöna: ofrecer cortar leña",
    "akûam-bušata: partir una leña a la mitad",
    "akûam-aia: matar, golpear y matar",
    "akûöng-ûta: romper una nuez con un martillo",
    "akûöng-ûsata: romper con un golpe",
    "akûöng-usöpata: golpear y romper en partes",
    "akûãš-ina: cortar en partes pequeñas como pan para la sopa, picar",
    "akûãš-ûna: golpear para prevenir que se escape un animal",
    "akûlöpata: Golpear en cualquier articulación y causar así un cojeo en ella, ya sea en la pierna, el brazo",
    "akûbala-mana: romper con golpes suaves",
    "akûpasawãna: Azotar, fustigar, golpear como con un bastón o correa, dejando latigazos",
    "akûpaia-ngaia: marcar un árbol con un hacha para encontrarlo más fácil",
    "akûp-asalagöna: Golpear cualquier superficie estirada provocando así un cosquilleo, por ejemplo, la grupa tensa o una. mejilla rellena",
    "akûp-öna: matar con un golpe",
    "akûp-önãmöni: casi matar",
    "ãgûp-öna-lagöna: intentar matar, hablar de matar",
    "akûp-önãki: el que mató y fue matado",
    "akûp-ãšû: Palmada como se hace con un niño en la mejilla o con un hombre en la espalda",
    "akûp-öngãmata: matar por otra persona",
    "akûp-undãtû: matar uno detrás de otro",
    "akût-ãsãna: cortar las ramas caídas de los árboles",
    "akuila: Cojear de un golpe, romper una pierna de un golpe",
    "akuš: oscuro como la noche, oscuridad",
    "akuš-cilix: Vengadores en sus conjuros: La noche, el espíritu de la oscuridad",
    "akuš-ana: oscuro, oscurece",
    "akuf-gãmata: estar a punto de romperse un hueso por un golpe",
    "akuf-yipû: romper ramas secas",
    "akul-a: transpirar, transpiración",
    "akum: venir para acá",
    "aku-y: venir más cerca",
    "kãtakga: no vayas a ningún otro lado",
    "akum-ia sa möni tûmûgaišinana: ¿Cómo es que siempre venís a pedirme que te ayude?",
    "akusimörana: Afilar, apuntar, cortar en punta como la punta de una lanza",
    "ali-tãgû: Dar de forma insolente, dar de forma burlona",
    "ali-ngûtãna: hablar insolentemente",
    "ali-na: Tratar a una persona con ligereza o de alguna manera grosera, o en broma. Insultar, molestar, hacer una broma",
    "ali-ta: grosero, impertinente, imprudente",
    "ali-ngãmata: insultar a una persona en vez de la otra",
    "ali-ndöška: Burlarse, reírse de, reírse burlonamente o en broma",
    "ali-ugûtãna: Hablar con rudeza de una persona o a una persona",
    "ajökul-ata: El perro ha terminado de mudar su pelaje, terminar de obtener una nueva capa de pelo, o desprenderse por completo del viejo pelaje desgreñado",
    "ajauaš-a: Enredado con la maleza como un bosque",
    "ajauaš-ka: lluvioso, mojado",
    "ajauaš-könata: se cargan de agua como las plantas durante el tiempo todavía húmedo",
    "aliûara: Girar de un lado a otro en el agua",
    "alak-ãr: Cristalino como el ojo en la muerte",
    "alak-öškû: sabor ahumado ya que el pescado colgaba a veces en el humo",
    "alagön-ia: mirar, observar",
    "alagön-aina: mirar mientras se camina",
    "alagön-a: examinar",
    "alagön-atas: lindo, linda, bonito, bonita, bello, bella, guapo, guapa, mirada atenta",
    "alagön-atwiiûã: Ver para morder y no entorpecer. Permitir morder",
    "alagön-iaina: espiar, explorar",
    "alagön-önnaka: no poder ver, ciego, no dar la mirada",
    "alagön-ãrûgata: tener dificultad para ver",
    "alagön-ûtauwãna: mirar fijamente",
    "alagön-ãtûkilla: sufrir, permitir partir. Mirar y ver partir",
    "alagön-ãkurû: Atento, curioso, observador, aficionado a mirar o ver",
    "alagön-ûkaia: subir y ver",
    "kwi ãruf hit-a û-pi: ¿dónde están los mejillones que vi antes de subir?",
    "hat-a ûdê ãruf wurû: Fui y quedaban muchos mejillones",
    "hat-adê könjima wêya: Lo vi irse antes de que muriera",
    "alagûm-aniaina: ir a buscar",
    "alagûm-ina: Ver o mirar mientras se sube, o antes de bajar",
    "alagûm-e: irse",
    "alagû-tölli: Mirar por todos lados. No mirar de forma constante",
    "alagû-yella: mirar por poco tiempo",
    "alagû-ûlûali: mirar una vez más",
    "alagû-wãta: haber visto hace un tiempo pero no vuelto a ver desde entonces",
    "alagû-nata: estar enojado, ponerse o estar caliente",
    "alax: picante",
    "alapön-a: Disminuir, hundirse en la calma como una brisa diurna al atardecer o un vendaval en cualquier momento, tirarse al agua",
    "alapön-ãmi: casi me caigo al agua",
    "alasãgû: Trozos de blanco, manchas blancas en la tierra que aparecen como humo y que a menudo se confunden",
    "ali: Cualquier pluma larga ornamental en la cabeza o el cuello de las aves",
    "ali-alisa: pedir como un regalo",
    "ali-möni: Molestar, o seguir molestando a una persona para que le dé algo",
    "alöngãmata: Ver y dejarlo, como se hace con un árbol cargado de hongos, para encontrarlo en otra ocasión",
    "algan-ama: tipo de foca que es muy ruidosa",
    "algan-ufka: ofensivo",
    "amia: Dibujar con los dedos sobre cualquier cosa para dejar sus marcas, dibujar, marcar",
    "amia-ta: dibujar en una cara recién oscurecida y dejar las huellas",
    "amiöngût: Arrancar con la uña, como un grano. Arrancar con las uñas",
    "amiöngût-ãlöpata: Romper o rayar en pedazos, rayar en muchos lugares",
    "amai-a: vomitar, estar enfermo",
    "amai-im: hongos en fruta o comida",
    "amaciû: Agrio, acre, astringente. No dulce, insípido",
    "amaš-ãgû: hambre, hambriento",
    "amaš-kurû: tener buen apetito",
    "amaš-dûpunata: ponerse débil por tener hambre",
    "amašãgw.ia: No se debilita ni se vence pronto, ni cede al hambre",
    "amak-a: la parte de atrás del cuerpo, atrás",
    "amag-êata: Surgir como ira y pasión en el corazón, enfadarse, estar enfadado",
    "amagön-a: útero, especialmente su contenido, embrión, brotes de hojas y flores",
    "amagön-ana: quedar en estado de embarazo",
    "amagön-ata: entrar en aguas tranquilas entre islas",
    "amagön-enata: listos para brotar en forma de capullos",
    "amalöx: Cauteloso, salvaje, receloso, sospechoso, consciente, advertido, alerta",
    "amalãg-adãtû: correr de el miedo o la sospecha",
    "öna: escapar",
    "öna-akilla: irse de cualquier lugar con sensación de miedo",
    "öna-atia: estar acostado o durmiendo consciente del peligro",
    "öna-alaiyi: Llamar a una persona como precaución contra la sospecha de ira",
    "aman-a: odiar, disgustar, estar en contra, hablar con rabia",
    "amapit-a: sobrino",
    "amapuš: ojos, cara",
    "amasãrar-um: primero, en el primer lugar, más pronto",
    "amata: Recoger un cable o ancla m atada, o una línea de pesca después de usarla",
    "amat-amboa: Tacaño, mezquino especialmente en lo que respecta a dar comida",
    "amat-öpi: Para izar, lleva un ancla a bordo",
    "amat-as: pacifico, amigable, gentil, hermoso, hermosa, guapo, guapa, lindo, linda",
    "amat-öswöci: Cruel, odioso, feo,  trata trata con odio",
    "amönata: Levantarse contra una persona con rabia y vehemencia. Odiar",
    "amöra: guanaco",
    "amãgû: Dulce, delicioso, con picazón. Esa sensación, el picor, cualquier queja de picor",
    "amagace-lux: Caliente, en venganza, muy ansioso y excitado. Furioso, apasionado",
    "amagace-llux: Intrépido, rápido, enérgico, impaciente de control",
    "amûs-ama: Pedir, suplicar comida a una persona que no está dispuesta a darla",
    "amuš-ata: separarse, irse",
    "amuš-wösel-ia: ser dividido en dos o tres lotes",
    "amur-yella: subir a la tierra un poco más alto e irse",
    "ammö-ci: quemar en un fuerte fuego en el suelo y las raíces de las plantas",
    "ammûk-û: Una agrupación. Una presa. Un racimo de mejillones, cuando los mejillones, las piedras, las caracolas, están todos pegados",
    "ammûgat: difícil de tragar, pegajoso, adhesivo",
    "ammux-pûkû: cocinar, poner en el fuego para cocinar",
    "ammux-tiyigata: traer obtener grupos de mejillones en cualquier recipiente",
    "amdeka: Arder bajo como un fuego brillante sin reponer",
    "anai-amun: un lugar protegido del viento",
    "anai-ökat: el lado resguardado de la casa",
    "anai-im ûsi: isla resguardada",
    "aniûali: Una persona cuyos parientes masculinos han muerto casi todos, por lo que es débil en cuanto a influencia, o está desprotegida frente a las lesiones",
    "ana: tener relaciones sexuales",
    "anemaköna: inquieto",
    "anöš-kûlömbi: Corteza joven de color oscuro y superficie lisa, utilizada para antorchas",
    "anãsa:  Masas de plantas musgosas que como alfombras cubren el suelo y las raíces de los árboles en los bosques",
    "anga-na: tirar, arrojar, dar, regalar gratuitamente como se hace con un montón de cosas no valoradas a cualquier persona que las quiera",
    "anga-manãtsiköri: tirar o arrojar afuera desde adentro",
    "anga-möci: tirar a un agujero o una casa",
    "anga-nköna: tirar al mar o a un bote",
    "anga-pûkû: tirar al fuego",
    "anga-mölãkû: tirar cosas así no se pierden",
    "anga-yãtû: lanzar cosas a una persona como regalo",
    "anci-kön: ahí, no lo ves?",
    "annû: tiene, tuvo, hace, hizo, deberá, hará, puede",
    "annû-könjin: pedir perdón, lo siento mucho",
    "annû-haia hûlû: extrañar mucho",
    "annû-nãgû: valorar, desear para uno",
    "annû-yãgû: Anhelar ver  en nombre de otra persona",
    "annû-nãkurû: sentir la ausencia o pérdida de un amigo o una cosa",
    "annû-ãki: último, el último, el último que queda",
    "annû-mala: el último día",
    "annungãmata: amar, desear, querer",
    "ap’aii: no me interesa",
    "apaigat-enata: Dejar de hacerlo, no gustar, evitar",
    "ap’iûölan: el cuerpo entero",
    "ap’iûalitas: bien formado, bien hecho, buena persona",
    "apa-köl: Plumón de aves utilizado como yesca. La piel de un pájaro con plumas, utilizada como banda para la cabeza",
    "apa-wöra: Cintas para la cabeza hechas de pequeñas plumas estrechamente unidas una tras otra",
    "api: El pequeño vello del cuerpo humano, como el que se encuentra en los brazos",
    "api-önnaka: persona desfigurada",
    "api-pai: hacia el cuerpo de una persona",
    "apisiû: no, ninguno ",
    "apis-êata: Terminar de chamuscar y así secar como corteza para antorchas",
    "api-dãra: todos, por todo el cuerpo",
    "api-töpa: no tener nada, pobre, desnudo",
    "apöna: el fondo de las cestas, barriles",
    "apöna-na: hacer una cesta desde abajo",
    "apör-i-nix: estrella, estrellas",
    "apös: determinado, determinada, feroz de rostro, feroz de maneras, salvaje, áspero estricto",
    "apauuša: Las encías, Las partes molidas en las articulaciones",
    "apûk-û: Dejar en paz, no molestar. Tratar con reverencia, con respeto",
    "apûk-aianata: desistir por un cambio de opinión, o por la duda",
    "apûtak-önata: remar hacia cualquier punto para llegar a él",
    "apût-û: Enfermedad de la boca y de los labios, en la que se forman patologías blancas o ampollas, acompañadas de una inflamación de la lengua y mucho picor",
    "apûkwia: Dejar solo, sin molestar. No molestar",
    "apuš: moco, mucosa",
    "apuš-atãgû: Tomar un cangrejo propio horneado o asado y comerlo",
    "apuš-yãtû: Dar cangrejos al horno a más personas que tres, o más de tres cangrejos a una persona",
    "apun: Las pieles de las aves marinas, especialmente de los cormoranes",
    "arãkur:  Un acantilado, un precipicio pedregoso",
    "arãlömb-i: Verde oscuro, azul oscuro, un azul profundo apagado, utilizado en el cielo y en la vegetación",
    "asia: gotear agua en un cubo con una taza de cualquier tipo",
    "ölata: todavía queda un poco de agua, no se drenó todo",
    "asiû ölan: alrededor, por todos lados, por todas partes",
    "asa sima: buscar agua",
    "asãsin-a: tener energía, victorioso, valiente",
    "asasinã-na: conquistar, superar",
    "asasinã-ãyella: Haber sido fuerte pero ahora no. Haber sido fuerte",
    "asata: cuando la marea empieza a bajar. Llevar fuera o lejos, como la marea cualquier objeto suelto en la orilla, o barco a la deriva en el mar, o como la corriente de un río hace cualquier objeto en su poder",
    "aseta: Traer, coger, ir a buscar, llevar agua en un cubo u otro recipiente",
    "asin: afuera en el aire libre, afuera de la casa",
    "asina: La fina trenza de tendones que se lleva enroscada al cuello como adorno",
    "asina-ta: Sacar la inundación de la tierra. Secar o librarse del agua como tierra inundada",
    "asis-iû: deshacer, desarmar",
    "asöla: Sumergirse y beber agua en una piscina poco profunda",
    "asölla: arena, playa con arena, arenoso",
    "asãkula: Para limpiar.  Limpiar como las nubes",
    "asãsiû: Persona que va en la oscuridad de la noche a matar personas",
    "asaui: El tiempo cuando sopla un nuevo vendaval del oeste, el sol brilla con fuerza y el cielo está despejado o casi",
    "askãsinana: crecer fuerte y grande como los niños, pájaros o bestias",
    "asnû: desganado para hablar o reír. Reacio, reticente, poco dispuesto",
    "asnû-na: no tener ganas o no poder hacer, hablar, responder, comer",
    "assia: Ir a buscar, ir a buscar agua (continuamente). Estar echando agua en un cubo",
    "assatûkãtaka: sacar una gran cantidad de agua en baldes, como cuando se vacía un pozo",
    "assãkaia: sostener o mantener agua dentro de un balde",
    "assi: Pequeña caracola, o arena y piedras o trozos de comida arrojados al agua para atraer a los peces a los anzuelos",
    "assi-köna: estar en una canoa pescando",
    "assalû: llevar baldes con agua a bordo",
    "assa-pûku: Poner al fuego agua u otro líquido en cualquier recipiente. Hervir, cocinar hirviendo",
    "astel: Una enramada de ramas verdes unidas apresuradamente como residencia temporal",
    "aswêa: contrario, obstinado, cruzado, rebelde",
    "atêakhaina: estar colgado, como una cometa en un árbol, o una cola en una cometa. Colgar o estar colgado como la pata rota de un pájaro que vuela.",
    "atêakhaina-kipa: estar casado",
    "atêax-kaia: colgar, colgar como una cesta vieja en una clavija",
    "atêax-möni: dejar colgado",
    "atêax-dãtû: colgar uno tras otro, o en un número considerable",
    "atêax-maniaina: balanceado, estar balanceado",
    "atai-agwia: estar colgado, unido, como cuando una cosa está atada a otra",
    "ata: agarrar, traer, encontrar, alcanzar",
    "ata-ûunna: partir, dejar un lugar para ir a otro a pie",
    "atakalangöra: libélulas",
    "atal-ãgû: Saltar, brincar, correr, como un bebé contento en los brazos de su madre",
    "atal-agöna: Tomar en la mano y sentir. Palpar con los dedos, como un pañero la tela, un panadero el pan",
    "atama: comer, devorar",
    "atama-asela: odiar, abusar, hablar mal de alguien",
    "atama-yamakûša: Hablar con enfado a una persona con intención de molestar, en referencia a su pariente recientemente fallecido, ya sea por su nombre o por otros motivos",
    "atam-ia: comer acostado",
    "atam-ãmöni: estar a punto de comer",
    "atetta:  Cortar un trozo o astilla. Quitar por medio de un corte",
    "atöng-a: Duro, severo, estricto, austero, especialmente en cuanto a la forma de hablar",
    "atöng-usiû: Romper con la mano por presión de los dedos o la mano",
    "atöng-usur-cãgû: Romper por encima como una galleta para un niño pequeño que no podía hacerlo por sí mismo",
    "atöli-i: golpear a las personas, como un matón",
    "atöli-ina: Actuar como un agresor. Tratar con rudeza e insolencia",
    "atöll-û: Enano, más corto de lo habitual. De crecimiento atrofiado, lento de crecimiento",
    "atömm-a: romper en pedazos, rasgar y arañar con los dedos y uñas como un gato enojado",
    "atömm-aiãtû: partir como panes y dar de comer a las personas",
    "atöpaiyãgû: poner a bordo algo para otra persona",
    "atöpaiyãgû-datû: poner en muchas canoas",
    "atãgû: Tomar para uno mismo. Tomar lo que es propio.  Amistad entre dos personas, acompañada de un cambio de regalos",
    "atãdãtû: un niño que crece rápido",
    "atûali: tomar y agitar con las manos",
    "atûi-skûla: Doblar, curvar. Tomar en la mano y doblar o presionar alrededor y hacer que se curve",
    "atûöš-i: Arrancar, retorcer. Romper con las manos, arrancar con una llave",
    "atûãš-šûna: Presionar a una persona con las manos para oprimirla o retrasarla",
    "atûšalatas-ãna: enderezar con las manos",
    "atûbãkašana: dibujar en arrugas con los dedos",
    "atûk-alana: Apretar, pellizcar con fuerza la piel y la carne entre los dedos",
    "atûköš-i: separar a dos personas peleando, defender",
    "atûg-ölaša: hacer ruido haciendo que las cosas se golpeen entre sí y así emitir un sonido al moverlas con la mano",
    "atûg-ãgulû: Volar, ir rápido, como una canoa cuando los remeros son vigorosos",
    "atûl-öša: exprimir, escurrir",
    "atûl-ö:  Torcer o descoyuntar. Girar completamente al revés",
    "atûm-ata: comer algo sin dejar nada",
    "atûm-ûtû: estar comiendo",
    "atûm-uri: Romper en la mano como un panadero su harina dura. Pulverizar. Ablandar presionando con la mano",
    "atûp-öšata: partir en dos con un palo largo",
    "atûp-öškûl-û: Reventar apretando. Romper y así reventar con la mano como un forúnculo",
    "atûp-ö-ata: Soltar como una cuerda para que lo que sostenía corra o caiga. Soltar el agarre. Dejar ir a un chico problemático",
    "atûp-öna: Pellizcar hasta la muerte, agacharse y matar, como a una mosca con los dedos. Estrangular, matar presionando con la mano",
    "atûp-isteka: Romper en fragmentos, como un papel infantil. Separar en pequeñas porciones",
    "atût-öwömmûtû: Sostener firmemente a una persona para evitar que se vaya. Sostener firmemente como una persona para otra un extremo de una trenza mientras la otra se trenza",
    "atûy-ella: comer un poco más o por un rato más",
    "aguila:  Llevar o presionar a una persona para hacer que sus piernas cedan y así poder tumbarla o hacerla cojear mientras uno lucha con otro",
    "atuina: Apagar el fuego pellizcándolo, como la mecha de una vela",
    "atux: remar",
    "atux-köna: seguir remando",
    "atux-ina: ir por el agua remando",
    "atux-köninata: remar una gran distancia",
    "atux-dãtû: dejar una canoa, como una esposa su marido",
    "atux-kûtãmãtû: sacar de águas profundas",
    "atux-teki: Encontrar mientras se rema. Encontrarse con cualquier cosa cuando se va en canoa",
    "atummöci: quemar a fuego bajo",
    "atur-êata: empinado, resbaladizo, resbalar, deslizarse hacia abajo, como una cosa de una mesa inclinada",
    "atur-i: empinado pero suave, deslizarse hacia abajo como un árbol inclinado",
    "atur-êir-mûtû: deslizar, deslizarse",
    "athaina: Partir, ir de un lugar a otro, por ejemplo en canoa o a pie",
    "atta: afeitar, cortar, pelar",
    "atwi-amigata: presionar los extremos para que se junten",
    "atwi-ella: dejar ir, soltar",
    "atwi-öšata: poner la mano en un agujero para taparlo",
    "atwi-öši: romper con las manos o los dedos",
    "atwi-ateka: bajar a un hijo problemático al suelo"
    ];

    const GLOSW = ["wurunur-kátaka: aumentar en número más y más, multiplicarse",
    "wur-un-ágú: tener mucho, ser rico",
    "w-nata: tener o ser muchos, numerosos",
    "wurun-ía: todavía quedan muchos",
    "wurú: muchos, una buena cantidad, suficiente",
    "wunna: ladrar como un pero, zoroo, lobo, chillar. hablarle a alguien con enojo",
    "wunat-a: unir juntando las partes rotas",
    "wulat-a: desatar cualquier nudo. desarmar cualquier cosa que esté atada",
    "wu(stötata: manejar como el humo y las llamas ante una brisa",
    "wu(s: un trozo largo un grande de piel, como el que se usa para sostener a un hombre trepado de un árbol cortando madera para las canoas",
    "wúpai: camino, ruta",
    "waalin-a: un hombre que no sabe hacer bien una canoa",
    "waali-kípa: guanaco adulto",
    "w-átur-ú: sobrino",
    "wátull-a: acercarse silenciosamente a un animal en el agua con la intención de matarlo",
    "wátauínaiw-a: el ancestral que no cambia. Nombre apropiado para Dios, indicador de eterno e incambiable",
    "wátaaia: el primero (sólo en tiempo pasado)",
    "wátátöp-an: algún tiempo atrás, y nunca más desde entoncss. sólo entonces y en esa ocasión",
    "wátágönn-ú: deseo",
    "wáta-ia: viejo",
    "wásin: palo con extremo chato como un cincel de un metro para sacar mejillones de las piedras",
    "wárú: cualquier espacio, chico o grande, debajo de piedras que sobresalen",
    "wáridátú: eco, hacer eco",
    "wápaac(na: ¡no a mí! ¡no me lo des a mí! ¡dejame en paz!",
    "wápana: ser nombrado, tener nombre",
    "wápan-gámata: tener otro nombre diferente del que se tenía antes",
    "wápan: mucho, pero",
    "yárum: demasiado pronto, demasiado temprano",
    "wápa: un nombre, una palabra",
    "wánux: madera podrida",
    "wánu(s-dátú: cavar una cantidad de pozos como para los postes de la reja de una casa",
    "wáni: pera (cuerpo)",
    "wánö-(sgúla: mejillones que están medio enterrados en el barro y son difíciles de agarrar",
    "wánarunnak-a: incómodo, desacostumbrado a hacer hoyos",
    "wánara: pozo de agua",
    "wánariya: estar cavando un pozo",
    "wána-ngút-á-löpata: rasquetear en un pozo, como hacen los perros",
    "wána-ina: caminar de paso, pasar",
    "wánía: tener el hábito, o frecuentemente, o estar ocupado cavando",
    "wámaköma: el pájaro de fuego",
    "wálú: comer cualquier cosa cubierta de caparazón, especialmente cangrejo, huevo",
    "wálápútas: experto en cortar ballenas",
    "wáláp-ía: estar ocupado cortando",
    "wágun: por encima, arriba",
    "wágú: agarrar, buscar",
    "wágöpi: tomar, buscar, meter cosas en una canoa, o bote. cargar",
    "wágöp-éya: a bordo",
    "wágönnak-a: hacer algo incorrecto, o de forma incorrecta",
    "wáganúpai: en lo alto",
    "wáganandaulum: del cielo, celestial. del techo, de la parte superior de cualquier cosa",
    "wádára: todos los caminos, cenderos",
    "wáköri: vejiga. cualquier cosa usada para contener aceite y grasas",
    "wás(a: más en número",
    "wá(ci: descortezar, descortezar una canoa",
    "wá: camino",
    "wöhy-a: puerta, entrada a una casa o habitación",
    "wötux-dátú: llevar una cantidad de canoas, una atrá de la otra",
    "wötúka: feo, de aspecto enfermiso",
    "wötát-ía: estar ocupado apilando",
    "wötek-a: llevar una canoa a la playa",
    "wötaw-a: honda",
    "wönágú: hacer una honda para uno mismo",
    "wösána: ratón, rata",
    "wösen-iáka: juego, escena representada como imitación",
    "wösellúpína: poner encima de otra cosa, como los troncos encima de los arbustos, de forma que se rompa",
    "wösellia: reposar como los huevos en un nido",
    "wörr-éata: caminar por el agua",
    "wörur: tronco",
    "wörú-báka: sin energía",
    "wör-íya: estar ocupado envolviendo a alguien muerto. estar reposando envuelto listo para la sepultura",
    "wöpúku: desparramar caracoles debajo de un fuego para que sirva de hogar donde el fuego puede ser hecho más fácilmente",
    "wön-gara: araña",
    "wgámata: cruzarse a una persona ando en direcciones opuestas",
    "wön-mö(ci: enterrar",
    "wönd-eka: cavar un pozo para formar un nido",
    "wönuf: lugar en el que cormoranes moñudos vuelan de un lado a otro constantemente siendo un blanco fácil para cazarlos",
    "wönisa: matar, ser herido por el lanzamiento de muchas flechas",
    "taiamöga: hacer envez de",
    "wöniz-köna-ina: andar agarrando pájaros pegándoles con piedras",
    "wönigú: pegar con una piedra",
    "wönig-ágú: apedreado",
    "wöniga-(cikú: lanzar un objeto de forma que se clave en algo, como una piedra en el barro",
    "wöniköng-úta: hacer un agujero pegando con una piedra, o un misil lanzable",
    "wöna-tú-w: algo usado para enrollar",
    "wönata: encontrar",
    "wönar-iya: pescar desde la orilla con una varilla",
    "wönan-a: tener sexo. actuar de una forma familiar o tomarse libertades de forma que demuestre los deseos propios de casarse",
    "wönamög-a: bendar",
    "wönama: rasquetear como los pájaros cuando buscan comida",
    "wönasi: baño de inmersión",
    "wönía: enrollar",
    "wöm: piojo",
    "w-mútú: comer cangrejo",
    "wöl hörákú: perderse",
    "wölha-ina: estar todos caminando",
    "wöllágulú: arrancar como sacando partes de una cerca",
    "wöllöng-a: hablar maliciosamente",
    "wöll-a: tirar abajo una edificación",
    "wölufk-ö-n: ponerse corrupto",
    "wöluswöle-n: desgastarse",
    "wölu-stusu-n: pequeño como la cintura de una avispa ",
    "wöluía: todos irse a dormir o a acostarse",
    "wölú-tulata: ser demasiado bajo",
    "wölú–p-éa: espacio descubierto",
    "wölúk-aia: apilar",
    "wölauu(syale-nata: flojo, suelto",
    "wölauiye-n: intimidado, desanimado",
    "wöláw-+ía: mejor",
    "w-élána: usar todos los materiales al construir algo",
    "wölás-íe-n: ponerse blanco, o cubierto por espuma",
    "w-imö-n: acuoso, líquido",
    "w-ágöna: todos sufrir, estar sufriendo",
    "w-ápö-n: ponerse muy rojo, estar ensangrentado, cubierto por sangre",
    "wöláputuru-n: estar acalorado",
    "wölápö-ci-n: seco como un río o pileta", 
    "wölápat-águ-n: disperso en el extranjero",
    "w-egána: culpable de muerte",
    "wölápaia: piedra",
    "wöláp-éata: estar desparramado",
    "wölám-ölamina: olvidarse todo",
    "wölágulú: alejarse, saltar",
    "wölákö-kúci: entrar a un barco viniendo de una canoa o bote",
    "wöláb-íápisi-n: sentir los pies muy inseguros como cuando uno camina por el borde de un abismo",
    "wölásátasi-n: estar muy cómodo con una persona",
    "wölása-ina: robarlo todo",
    "w-bagú: estar todos agradecidos, a gusto, contentos",
    "wölácgömaka: agotar todos los materiales al trenzar",
    "wöláci-sápína: agotar todas las piedras al lanzar",
    "wölö-pásu-n: saber, ser conscientes de algo",
    "w-sikú: mantener todo en secreto",
    "wölisa: matar un animal grande golpeándolo con muchas flechas de sobra",
    "wölikö-n: mojarse",
    "wöli-kímú: poner",
    "w-lése-n: poroso",
    "w-stai-n: cubierto de escarcha",
    "wölici-gata: pegarse",
    "wölamburu: ver mejor",
    "w-lagöna: mirar y así saber todo sobre algo",
    "w-túgata: irse y llevarse todo de forma que no quede ninguna canoa",
    "wöla: desatar, desarmar ",
    "wöl: terminar",
    "wölai-yi: llamar a todos",
    "w-ingena: asustarse mucho, estar muy asustado",
    "wölaiá-cina: estar expuesto al viento",
    "wölaii-kú: raspar todo",
    "w-gútata: acercarse mucho al punto de estar unidos",
    "w-lasa: terminar de succionar todo el jugo de una naranja",
    "wölaie-si: romper todo",
    "w-ki: terminar de come todo",
    "w-lla: dejar todo",
    "w-m-ana; ser todo blanco",
    "wölaia-kö-n: achicarse",
    "wölaiai-gu-nata; estar cubierto de lágrimas",
    "w-dasi-n: mañoso, ponerse delicado con lo que uno come",
    "wölítás-in: lugar lindo y despejado",
    "w-inur-kátaka: crecer, ponerse cada vez más hermoso",
    "wölítas: lindo, hermoso, apuesto, bueno, exceente",
    "w-a-lagöna: ser de apariencia hermosa",
    "w-maala: un día lindo",
    "wölíl-ana: terminar de construir",
    "wölía: acostarse todos",
    "wöléw-a: chico, pibe",
    "wölédág-ana; crecer",
    "wöléa: terminar de hacer",
    "wöx-mína: hacer regularmente",
    "w-mútú: sentarse",
    "wöx-gámata: hacer lo incorrecto",
    "wöxk-öna: navegar cargando cosas sobre la piel o la falda",
    "w-ögata: juntarse, encontrarse",
    "wökur: orina",
    "w-pöna: tener una debilidad o propensión a orinar",
    "wökis: hueso usado para separar la leña",
    "wökataka: ser de largos distintos, ser irregular",
    "wökat-anía: pasar por agua",
    "w-anapömur: estrella de mar",
    "wöstág-hain-ágú: estar ocupado haciendo cosas para uno mismo",
    "wöstágú: trabajar, hacer, manufacturar",
    "w-kurú: dispuesto a trabajar",
    "w-duf: débil, inhabilitado para trabajar",
    "wöstágönnak-a: vago",
    "wöstágatuárügata: arruinar",
    "wöstöx-köna: trabajar",
    "w-dátú: hacer muchas cosas una detrás de la otra",
    "wöstög-ágú: trabajar para uno mismo",
    "wöstegur-cella: haber hecho todo",
    "w-míkingale-nata: alegrarse o felicitarse por haber terminado un trabajo",
    "wösteg-ata: problemas, perplejo, preocupado",
    "wöstek-a: lavar estando en tierra",
    "wöskösú-kúci: llevarte tus cosas a bordo",
    "wöskösan-ía: estar ocupado juntando cosas para poder guardarlas de forma segura",
    "wösa: ir a la deriva",
    "wistöl: pequeño temporal",
    "wiss-a: inclinarse hacia atrás para enderezarse ",
    "w-öngusiú: romper algo al doblarlo demasiado",
    "wisdátú: sin descanso, ansioso, demostrar ansiedad o inquietud de ir y venir de tanto en tanto de ver o escuchar como lo hace una persona expectante o ansiosa",
    "wisa: madera podrida de un color rojo profundo",
    "winni-úalan: todos los familiares de uno",
    "wi-gámata: hacer en lugar de otro, reemplazar",
    "wicóa: el estornino de pecho rojo de las Islas Malvinas",
    "waim: hermano mayor",
    "waik-ul: punzones utilizados para hacer canoas",
    "waikíp-a: hermana mayor",
    "wai-aala: arrollo",
    "waii-sin: aquellas partes del país que están protegidas del mar abierto por isalas",
    "waia wurisin: tierra abundante en arrollos",
    "waiata-ásana: regocijarse, estar contento",
    "waian-a: arco",
    "w-aala: arquero",
    "waiamun: tu hermano",
    "waiaman-a: llegar o ir primero, ser el primero, primerear ",
    "waiai-im: ensenada",
    "w-aala: focas jóvenes ",
    "wíy-in: tribu de patos, pato gris",
    "wíná-möni: traicionar",
    "wína: mosca",
    "wílauíla: alchón de mar",
    "wíufgai-a: vivir cerca",
    "wíus-ákurú: dado a hablar con admiración",
    "wíusa: halar con alabanza, hablar con elogio",
    "wíaa-gátú: promover sentimientos o palabras de envidia a través de una conducta egoísta",
    "wíát-akálana: abrir",
    "wíálöpata: cortar",
    "wíágungaia: poner algo blanco",
    "wíágun-ana: tratar con crueldad",
    "wíágaia: permitir, no impedir o prevenir",
    "wiású: traer a la bahía, ladrar como los perros a un animal en la bahía",
    "wíös-gaia: colocar como una puerta en su lugar",
    "wíip-anasú-möni: poner algo sobre su borde",
    "wíipanas-ana: tirar una piedra de canto de forma que se hunda bien a lo largo de la superficie",
    "wíin-gana: rechazar un regalo",
    "wíina: pescar con una línea",
    "wíimágú: ponerse algo tejido en el cuello",
    "wíila-ina: renguear",
    "wíix-g: cortar una segunda vez",
    "wíig-ata: cortar un árbol con un hacha",
    "wíete-na: permitir hacer canastas",
    "wíerri: sacudirse al cambiarse como los pájaros sus plumas",
    "wíepat-eg: caminar cerca",
    "wíeng-a: engañar, inducir una falsa impresión",
    "wíella: favorable",
    "wíat-a: tejer",
    "wíapat-eka: acercar",
    "wíapi: cerco, reja",
    "wíapakalári-na: hacer algo en grandes cantidades",
    "wíapé-ata: cercar cualquier objeto",
    "wíamúk-ána: estirar",
    "wíamöt-a: precipicio",
    "wíamas-a: sufrir",
    "wïamman-asinana: dejar escapar en un estado de asombro",
    "wíaman-ana: dar vida, restaurar la vida, curar", 
    "wíamala-na: dar mucho, dar más a uno que a otro",
    "wíamacina: hacer espacio",
    "wíam-íkü: actuar como un rival, emular",
    "wíakwía: talat árboles",
    "wíakö-nanténaka: caminar buscando algo",
    "wíakananaina: caminar por el borde",
    "wíakalaná-kápa: el nombre de una estrella en particular",
    "wíakalana: espiar, mirar furtivamente",
    "wïaiella: quedarse un rato",
    "wíaiana: cielo azul",
    "wíaina: estar flojo y por eso moverse con facilidad",
    "wéyömi: pasto largo como la tusac ",
    "wénatúmútú: vaciar, evacuar",
    "wélix: arcilla especialmente de colores",
    "wéaunína: un tipo de ballena que no tiene el aleta de atrás y tiene un hueso largo en la boca",
    "wéa: hígado",
    ];

    const GLOSY = ["yulla: pierna",
    "yukaia: protegido, un lugar protegido",
    "yous úa (m) y-kípa: mentiroso, farsante, mitónimo",
    "you: mentira",
    "youau-ína: cangrejo",
     "y.-ö-nata: vago",
    "youasiye-lla: mentir ",
    "youasi-m: mentir antes de irse",
    "youasi-mútú: mitomanía",
    "youasin-köna: mentir navegando en canoa",
    "youasan-a: mentir",
    "youara: mandíbula de ballena",
    "yaalan: perímetro",
    "yátu-réata: divergente; canoa vieja",
    "yátullá-köna: sumergido en agua, a punto de hundirse", 
    "yátulla",
    "yátátü: chispa",
    "yátus-ía: hablar",
    "y-aina: hablar en movimiento",
    "y-gana: charleta",
    "yätú: distribuir, más de tres cosas",
    "yatö-llátú: labio cortado",
    "y-ndalis: barullo",
    "yát-ta: dar acostado",
    "yás-ita: chismoso",
    "yártuntöpa-ia: recién",
    "yárum-gala: pibe",
    "y-u-nata: renovado",
    "yárú, yárum: renovado, fresco",
    "yápulla: pacífico",
    "yápá-cál: ser superior, como si fuese su deidad, pero sin creer en dioses, espíritu de los muertos",
    "yápis: chismoso",
    "y-n-köna: éxito en la pesca",
    "y-n-gámata: parcialmente exitoso",
    "y-yella: supo ser exitoso",
    "yámú: experto",
    "yámöra: boca puntiaguda (quizá tipo hocico, o pico)",
    "y-gámata, möni: ponerse blanco",
    "yágü: pálido",
    "yágöla-sa: bochornoso",
    "yága, yáka: copia, imitación",
    "yágaiámöni: en la punta de la lengua (expresión)",
    "yágaia halasa: impaciente por escuchar instrucciones",
    "yágaiunnak-a: incapaz de enseñar",
    "yágaiatus-úwö-n: alegrar a la gente con buenas noticias",
    "yágaiatú-aigal-e-n: enseñar con metáfora, ejemplo",
    "yágaia-ina: caminar hablando",
    "yáduf: de habla débil",
    "yádömull-a: profundo", 
    "yáköpata: sanar",
    "yáki: líder, primerizo",
    "yásun: barba, vello facial",
    "yácauwi: estrella",
    "yáci: desprotegido del viento",
    "yöndaulum: de la boca, la punta de algo",
    "yöndákú: rescatar una canoa de un pozo",
    "yöndöx-köna: persistir",
    "yönatöp-a: en medio de",
    "yön-gan: en el camino",
    "yöná maalunc(i-töpan saingana: salir a la tarde",
    "yön: extremidad",
    "yös(mötta: un pequeño ave marina de color oscuro",
    "yetan’-aias(: inteligente para hacer canastas",
    "yntegata: hacerse experto en algo",
    "yúnata: aprender y ser bueno en algo fácilmente",
    "yös(man-önnaka: hombre experto en cualquier tipo de trabajo",
    "yös(d-ára: todas las manos, todos los cuerpos. Tener manos grandes",
    "yüpöna: _manos de manteca_ hombre con manos débiles",
    "yösk-a: isla",
    "yös(ú-kú: dedos cortos",
    "yös(-áki: con la mano",
    "yös(önnaka: tener manos malas, particulares",
    "yös(öl-aiamalim: perro",
    "yös(ö-gat-a: cortar un pedazo de madera usado para recostarse en la playa para transportar una canoa",
    "yös(i: romper",
    "yös(ama: mar rosa",
    "yös(é-ata: partirse en dos",
    "yös(: mano, dedo",
    "yipanus(: el borde",
    "yipaias(a: cubrir cortando ramas y desplegándolas",
    "yin-kön: estar cruzando justo cuando pasa una canoa o una persona en una",
    "yingin-gas(tágú: atravesar el miedo",
    "y-álana: llorar con miedo",
    "méa-köna-ta: miedoso, tímido ",
    "yinginá-kamátú: levantarse, despertarse por miedo",
    "yingin-ía: acostarse con miedo. tener miedo mientras está acostado",
    "yinun: partir, pues es un final particular para la mayoría. Antes o todavía no",
    "atú-y: antes de una comida",
    "yinú: lamentarse por los muertos",
    "yiná-kaia: ser rápido para cruzar",
    "yina: cruzar en canoa",
    "y-ta, möni: cruzar en un grupo de personas, una atrás de la otra",
    "yinía: ir",
    "yimbgasella: apoyar, como una madre la comida a sus hijos",
    "yimbög-útata: abrir un canal entre islas para ver cómo uno cambia de posición",
    "yimbá-m: masticar, sostener en la boca",
    "yimba-ina: sostener entre los dientes mientras uno anda por ahí",
    "yimb-ia: tener en la boca mientras duerme, o está recostado",
    "y-imú: romper en porciones y dividir",
    "yill-a: masticar o comer masticando algo que es duro",
    "yigarag-ágá: compartirse a uno mismo, o algo propio",
    "yigaraz-köna: comer en una canoa",
    "yiftek-a: arrancar",
    "yifta: pobre de sentidos",
    "yif: crecer, terminar en un borde estrecho",
    "yibalanena: masticar, ablandar, destruir mordiendo",
    "yatun-köna: estar ocupado navegando en canoa",
    "yatund-eka: hacer",
    "yetú-m: estar siempre ocupado",
    "yesepös: un viento frío, fuerte. clima nublado, especialmente del este",
    "yepu-x: amigo, compañero",
    "yepúgöna: querer, amar",
    "yepaan: la parte baja de la espalda, donde están los riñones",
    "yepatúgur-kátaka: acercarse",
    "yepatagwía: estar cerca",
    "yepateka: cerca, al alcance de la mano",
    "yeugá-gámata: ser engañado, tener o formar una idea errónea",
    "yenga: pensar, tener una opinión, ser persuadido de algo que no es verdad",
    "yembön-á-kípa: la madre de un bebé chico",
    "yemböna: el estado de tener un hijo chico",
    "yellun: consecutivo. Despúes de una comida",
    "yellaus(ata: abandonar una isla dejando a los visitantes encarcelados",
    "yellá-míkú: escapar volando",
    "yellágú-leni: escapar buceando",
    "yellá-kátaka: irse, abandonando a alguien",
    "yelláki: olvidado. dejar algo olvidado, abandonado",
    "yell-enata: estar muy sucio. enchastrado",
    "yel-ata: partir en canoa",
    "yelaiágú: clima calmo. en estado de calma",
    "yelaia: muchos. hay muchos",
    "yeku-s(: puntas de pedernal para flechas",
    "y-hya: una puerta pequeña",
    "yeká-bix: cualquier pájaro pequeño",
    "yeki: comer pescado",
    "y-aina: comer pescado mientras caminas o navegas en canoa",
    "y-tö-s-, sa tambaa: Qué excesivamente malo que eres",
    "yekam-galanda, hiúös(töx-mütü: ¿Fue poco el tiempo que estuve en el trabajo?",
    "yekadáb-i: tía",
    "yekas(ökus(: una pequeña gaviota de orilla con piernas rojas",
    "yekas(an-a: persona asesinada a flechazos",
    "yeka: pequeño",
    "yekai-aii: estar comiendo pescado estando acostado",
    "yekéa-nnaka: nunca haber comido pescado",
    "yat-apín-ix: el borde de algo",
    "yakap-alári: enorme",
    "yanágú: resolutivo",
    "yana: querer",
    "y-anía: estar determinado a hacer algo",
    "yammina: lastimar, agredir de forma física a su esposa",
    "yamúk-a: fuera del alcance. inalcanzable",
    "yamaat: mariposas",
    "yamác(i: habitación, espacio, ausencia",
    "yamasaa-nari: atar algo en el agua",
    "yamasá-köna: atar estando a bordo",
    "yamasi-tágú: agarrar, tomar",
    "yamasir-c(ella: atar por un tiempo corto",
    "yamaseta: atar",
    "yamasa: asegurar algo atándolo",
    "yamasai-ella: atar algo e irse. atar algo antes de irse",
    "yamas-ía: estar atado",
    "yamanú-wa: hombre",
    "yamaná-k: mujer",
    "y-dára: mucha gente, todo el mundo",
    "y-möni: estar vivo, bien, no lastimado, sano",
    "y-magátú: estar bien de salud",
    "yaman-’apisiú úsin: una tierra sin habitantes",
    "y-aala: homnre, especialmente yagán",
     "yamana: Humanidad. con este término los yaganes se distinguían del resto de la gente que hablaba otros idiomas",
    "yamalúwána: tratar a un familiar con una familiaridad que se considera apropiada sólo usar con personas con quienes sería apropiado casarse",
    "yamal-’úsi: costa abierta la mar",
    "yamalári: maravilloso, prodigioso, excelente, inmenso, muy energético",
    "yamalin-dára: populoso, lleno de gente",
    "yamalim-ata: irse, marcharse en canoa",
    "yamali:grupo de personas, especialmente un grupo que se mueve junto",
    "yamala: grande, inmenso, perteneciente al mar abierto",
    "yamakus(a: hablarle a los vivos en una forma en la que se le habla a los espíritus muertos",
    "yamas(k-ú: generoso, liberal, bueno, amable",
    "yamai-na: amplio, grande",
    "yamin-a: blanco",
    "yamíkwía: rellenar, llenar",
    "yamíkú: bolso de piel para sostener cabezas de lanza",
    "yamíc(aina: caminar de prisa",
    "yalári: firme, con firmeza",
    "yalös(tega: atar una canoa a otra para que sea llevada por la otra",
    "yaka-nan: cercano",
    "yabaila: tener poder para hablar con elocuencia",
    "yas(aana: chisme, mentira",
    "yaénan: el principio del invierno",
    "ya: la boca, el labio, cualquier parte de la boca",
    "yóá-kurú: dejarse llevar por el enojo",
    "yóidág-a: fuerte, vigoroso, energético, capaz, valiente, corajudo",
    "yóagátú: insatisfecho, enojado",
    "yóa: con enojo",
    "yóaiam-ánúwa: el primerizo, el líder",
    "yóaiaman-a: ser el primero, el tempranero",
    "y-a-ánan: la canoa que va delantera",
    "yaiy-a: con la boca",
    "yailó: la garganta o cuello, especialmente de cisnes o pájaros con cuello largo",
    "yaidas: tener mal gusto respecto a la comida",
    "yaiaal-ana: haber sabido algo, recordar vagamente",
    "yai-iúain: el borde de algo",
    "yïya: dejar el encla, pero luego irse directamente",
    "yít-etata: morder, separar, romper con los dientes",
    "yís-g: masticar, comer de vez en cuando",
    "yísá-duf: no tener fuerzas para masticar",
    "yïsönnaka: incapaz de masticar, no haber comido",
    "yís-a: comer, masticar",
    "yípun-gámata: hacer, ocasionalmente, ni muy seguido, ni usualmente",
    "yípun: la cresta de una colina, montaña, banco, o cualquier otro objeto",
    "y-ata: girar de forma que mires hacia el mar, el viento o cualquier otro objeto",
    "yípu(si: comer mejillones que no tienen sustancia",
    "yípárú: separar con los dientes como un hombre un pedazo de hueso de ballena en tiras",
    "yípöskúl-a: morder de forma que todo lo que esté atado se afloje y libere",
    "yípön-ía: matar mordiendo",
    "yípö(s-ata: separar con los dientes propios",
    "yípat-a: arrancar, como se arrancan las flores del campo",
    "yípa-istöpan, hip atömudé: comemos inmediatamente",
    "yípa-i: para la boca, para uso presente como cuando un hombre come inmediatamente lo que agarra",
    "yínu(sata: limpiar un cuerpo comiendo toda su carne",
    "yím-gala: aflojar, desatar con los dientes",
    "yím-akaia: eperlano pequeño, o un pez como el eperlano",
    "yíméak-ána: pelar con los dientes",
    "yílu(sata: chupar todo",
    "yíl-a: renguear, tener una rodilla débil",
    "yígul-a: arrancar con los dientes un hilo, un clavo, u otra cosa",
    "yígútata: estar estrechamente cerrado como los párpados",
    "yíkú: una pequeña ranura",
    "y-öna: movimiento suelto, estar relajado, tener diarrea",
    "yésana: apuntar para obtener un objeto. hacer algo rápido o lento, bien o mal, con un objeto",
    "yéa(söx: cormorán moñudo que principalmente arraiga en los árboles",
    ];

    return (
        <div>
            <NavBarReal/>
            <h1 className='title-glosario'>GLOSARIO</h1>

            <div className='letras'>
                {LETRAS.map(letra => <a href={`#${letra}`} key={letra}>{letra}</a>)}
            </div>

            <div className='glosario-container'>
                <div>
                    <h2 className='letter' id='A'>A</h2>
                    {GLOSA.map((frase, i) => <p className='quote' key={i}>{frase}</p>)}
                </div>

                <div>
                    <h2 className='letter' id='W'>W</h2>
                    {GLOSW.map((frase, i) => <p className='quote' key={i}>{frase}</p>)}
                </div>

                <div>
                    <h2 className='letter' id='Y'>Y</h2>
                    {GLOSY.map((frase, i) => <p className='quote' key={i}>{frase}</p>)}
                </div>
            </div>
        </div>
  )
}

export default Glosario;